basket/urls.py
from django.urls import path
from .import views

app_name = 'basket'

urlpatterns = [
    path('basket/', views.view_basket, name='view_basket'),
    path('add/<int:product_id>/', views.add_to_basket, name='add_to_basket'),
    path('update/<int:product_id>/', views.update_basket, name='update_basket'),
    path('remove/<int:product_id>/', views.remove_basket, name='remove_basket'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<slug:slug>/', views.blog_details, name='blog_details'),
]

little_gem_felts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('basket/', include('basket.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='store'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

store/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    """
    Docstring for Category
    Category names for  use in Product as FK
    """
    name = models.CharField(max_length=50, unique=True)

    class  Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Docstring for Product
    Model containing product data. Images are contained in Image as FK
    Access images as product.images.all()
    Category is FK and on_delete is protect found on docs:
    https://docs.djangoproject.com/en/6.0/ref/models/fields/#django.db.models.ForeignKey.on_delete
    """
    name = models.CharField(max_length=200, blank=False,)
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    main_category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    sub_category = models.CharField(max_length=200, blank=True, null=True)
    stock_level = models.IntegerField(default=0, blank=False, null=False)
    delivery_cost = models.DecimalField(max_digits=5, decimal_places=2)
    promoted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    # suggestion by AI - needed to return the object
    # with primary_img or first image and not the string
    # so that it can be used in the basket view easily
    @property
    def primary_image(self):
        """Returns the primary image or first image if no primary is set"""
        return self.images.filter(primary_image=True).first() or self.images.first()

class Images(models.Model):
    product = models.ForeignKey(Product, on_delete= models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='products/', height_field=None, width_field=None, max_length=None)
    position = models.IntegerField(default=0, blank=True, null=True)
    primary_image = models.BooleanField(default=False)# image for card and first to display in details

    class Meta:
        ordering = ['position']  # Changed from 'product' to 'position'

    def __str__(self):
        return f"{self.product.name}'s image at position: {self.position}, Primary: {self.primary_image}"

store/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.contrib import messages
from .models import Product

# Create your views here.
def all_products(request):
    """
    Docstring for all_products
    Retrieve all products from Product Table and filter
    if the filter input has been submitted. Show main_category
    items if buttons are pressed.
    Tutorial adapted: https://www.makeuseof.com/add-search-functionality-to-django-apps/ 
    :param request: Description
    """
    products = Product.objects.all()
    promoted_products = promoted_products = Product.objects.filter(promoted=True).prefetch_related('images')[:3]
    filter_query = request.GET.get("filter_input","").strip()
    category = request.GET.get("category","").strip()
    sub_category = None
    
    if category.lower() != "all":
        products = products.filter(main_category__name__icontains=category)

    if filter_query:
        products = products.filter(Q(name__icontains=filter_query) | Q(main_category__name__icontains=filter_query) | Q(description__icontains=filter_query))

    context = {
        'products':products,
        'promoted_products':promoted_products,
        'filter_input':filter_query,
        'category':category,
               }
    return render(request, 'store/products.html', context)





def product_detail(request, product_id):
    """
    product_detail taken from BoutiqueAdo
    
    """
    product = get_object_or_404(Product,pk=product_id) # Grab all the Product objects
    # The context returned to the view...
    context = {
        'product': product,
    }
    return render(request,'store/product_detail.html',  context)

store/templates/store/product_detail.html
{% extends "layout.html" %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/store.css' %}">
{% endblock extra_css %}
{%block latestAdditions%}
{%endblock latestAdditions%}
{% comment %} The latest additions section is pulled from layout.html {% endcomment %}
{% block titles %}
<h1>Product details</h1>
{% endblock titles %}
{% block content %}
<p>{{product.main_category}}...{{product.sub_category}}</p>
<section class="product-section">
    <div class="store-container">
        <div class="wa-grid wa-gap-2" style="--min-column-size: 200px;">
            <div class="title">
                <div class="images">
                    <img src="{{product.primary_image.image.url}}" alt="">
                </div>
                <h2>{{product.name}}</h2>
            </div>
            <div class="description">
                <p>
                    {{product.description}}
                    <span><strong>{{product.price}}</strong></span>
                </p>                
                <div class="add-to-basket">
                    <form action="{% url 'basket:add_to_basket' product.id %}" method='POST'>
                        {% csrf_token %}
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        <input type="number" name="quantity" id="id_quantity" {% if product.stock_level < 1 %} value = "0" {% else %} value="1"{% endif %} min="0"max="{{product.stock_level}}">
                        {% if product.stock_level < 1 || id_ %}{% endif %}
                        <button >Add</button>
                    </form>
                </div>
            </div>
            
            
        </div>
    </div>
</section>
{% endblock content  %}

store/templates/store/products.html
{% extends "layout.html" %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/store.css' %}">
{% endblock extra_css %}

{% comment %} The latest additions section is pulled from layout.html {% endcomment %}
{% block titles %}
<h1>Welcome to the Shop</h1>
{% endblock titles %}
{% block content %}
<section class="product-section">
    <div class="shop-filter">
        <div class="category-change">

        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn all-btn' href="?category=all">All</wa-button>
        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn kit-btn' href="?category=kit">Kits</wa-button>
        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn lamp-btn' href="?category=lamp">Lamps</wa-button>
        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn box-btn'href="?category=box">Boxes</wa-button>
        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn bag-btn'href="?category=bag">Bags</wa-button>
        </div>
        <div class="category-change">
            <wa-button size='small' class='round-btn tool-btn'href="?category=tool">Tools</wa-button>
        </div>
        <div class="filter-container">
            <form action="{% url 'store:store' %}" method="get">
                <wa-input placeholder='Filter' size='small' type='text' name='filter_input' value="{{filter_input}}"></wa-input>
                <button type="submit" class="search-btn">🔎</button>
            </form>
        </div>
    </div>
    <div class="store-container">
        <div class="wa-grid wa-gap-2" style="--min-column-size: 200px;">
            {% for item in products %}
            <div>
                <wa-card class="card-overview">
                    <img slot="media" src="{{ item.images.first.image.url}}" alt="" />
                    <h3>{{item.name}}</h3>
                    <p>{{item.description}}</p>
                    <wa-button size='small' class='footer-btn' href="{% url 'store:product_detail' item.pk %}" variant="brand" pill><i class="fa-solid fa-bag-shopping"></i>£ {{item.price}}</wa-button>
                    {% comment %} <wa-button size='small' class='footer-btn' href="{% url 'store:product_detail' item.pk %}" variant="brand" pill>read more</wa-button> {% endcomment %}
                </wa-card>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content  %}