blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<slug:slug>/', views.blog_details, name='blog_details'),
]

little_gem_felts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('basket/', include('basket.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# add note for pulling from the early walkthrough
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    content = models.TextField()
    img = models.ImageField(blank=True ,upload_to=None, height_field=None, width_field=None, max_length=None)
    start_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    end_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    location = models.CharField(max_length=200)
    is_event = models.BooleanField(default=False)
    allow_comments = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)


    class Meta:
        ordering = ['date_created']

    def __str__(self):
        return f""


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['date_created']

        def __str__(self):
            return f"Comment {self.content} by {self.author}"

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def blog(request):
    """
    Docstring for blog
    A test view to return the blog page    
    :param request: Description
    """
    return render(request, 'blog/blog.html')

def blog_list(request):
    """
    Docstring for blog_list
    A view to return all blog articles   
    :param request: Description
    """
    posts = Post.objects.filter(publish=True).order_by('date_created')
    return render(request, 'blog/blog_list.html', {'posts': posts})

def blog_details(request, slug):
    """
    Docstring for blog_details
    A view to return the details of a single blog    
    :param request: Description
    """
    post = get_object_or_404(Post, slug=slug, publish=True)
    return render(request, 'blog/blog.html', {'post':post})

blog/templates/blog/blog.html
{% extends "layout.html" %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">{% endblock extra_css %}
{% block latestAdditions %}{% endblock latestAdditions %}
{% block content %}
<section class="blog-section">
  <div class="wa-grid wa-gap-l" style='--min-column-size:300px;'>
    <div class="title wa-span-grid">
      <h2>{{post.title}}</h2>
    </div>
    <div class="slug">
      <h3>{{post.slug}}</h3>
    </div>
    <div class="image">
      <img src="" alt="blog post image">
    </div>
    <div class="wa-span-grid text">
      <p>{{post.content}}</p>
    </div>
    <div class="date-edit-author">
      <span>written by: {{post.author}} | </span><span>first published on: {{post.date_created}} | </span><span>last edited on: {{post.date_updated}}</span>
    </div>

  </div>
</section>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends "layout.html" %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock extra_css %}
{% block latestAdditions %}{% endblock latestAdditions %}

{% block blogAndEvents %}
<section class="blog-and-events-section">
  <div class="blog-event-container">
    <div class="blog-container">
      <h2>Blog: What's on in the workshop</h2>
      {% for post in posts %}
        {% if post.is_event != True %}
            <div class="blog-item">
                <h3>{{post.title}}</h3>
                <p>{{post.slug}}</p>
                <p>{{post.content}}</p>
                <p>{{post.date_created}}</p>
                <wa-button size='small'class="blog-btn" pill href="{% url 'blog:blog_details' post.slug %}">Read more</wa-button>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="event-container">
      <h2>Events: Join us at our next event</h2>
      {% for post in posts %}
        {% if post.is_event == True %}
            <div class="event-item">
                <h3>{{post.title}}</h3>
                <p>{{post.slug}}</p>
                <p>{{post.content}}</p>
                <p>We will be at <strong>{{post.location}}</strong></p>
                <p>{{post.date_created}}</p>
                <wa-button size='small'class="event-btn" pill href="{% url 'blog:blog_details' post.slug %}">Read more</wa-button>
            </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</section>
{% endblock blogAndEvents %}
{% block content %}
<!-- Additional homepage content if needed -->
{% endblock content %}