basket/urls.py
from django.urls import path
from .import views

app_name = 'basket'

urlpatterns = [
    path('basket/', views.view_basket, name='view_basket'),
    path('add/<int:product_id>/', views.add_to_basket, name='add_to_basket'),
    path('update/<int:product_id>/', views.update_basket, name='update_basket'),
    path('remove/<int:product_id>/', views.remove_basket, name='remove_basket'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<slug:slug>/', views.blog_details, name='blog_details'),
]

little_gem_felts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('basket/', include('basket.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='store'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

templates/base.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

{% endblock content %}

templates/layout.html
{% load static %}
{% url "home" as home_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.webawesome.com/21ebcafd391742ca.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4d2d2c68b5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="shortcut icon" href="{% static 'images/favicon.png'%}" >
    <link rel="stylesheet" href="{%static 'css/base.css'%}">
    {% block extra_css %}
    {% comment %} load extra page CSS for page specific styling {% endcomment %}
    {% endblock extra_css %}
    <title>LittleGemFelts</title>
</head>
<body>
    <header>
      <nav class='navbar'>

      <wa-button appearance='plain' size='large'href='{% url 'home'%}'>LittleGemFelts</wa-button>

      <ul class="menu">
        <li>
          <wa-button class="nav-btn" href="{% url 'store:store'%}">Shop</wa-button>
        </li>
        <li>
          <wa-button class="nav-btn" pill>Event</wa-button>
        </li>
        <li>
          <wa-button class="nav-btn" pill href="{% url 'blog:blog_list'%}">Blog</wa-button>
        </li>
        <li>
          <wa-button class="nav-btn" pill href="{% url 'basket:view_basket'%}">Basket</wa-button>
        </li>
        <li>
          {% if user.is_authenticated %}
          <wa-button class="nav-btn" pill>{{user.username}}'s Profile</wa-button>
          {% else %}
          <wa-button class="nav-btn" pill>Log-in / Sign-up</wa-button>
          {% endif %}        
        </li>
      </ul>
      </nav>
    </header>
    <main>
      {% block cta %}
      {% comment %} homepage call to action section here {% endcomment %}
      {% endblock cta %}
      {% block titles %}
      {% comment %} Title block to appear above latestAdditions (for Shop) {% endcomment %}
      {% endblock titles %}
      {% block latestAdditions %}
      <section class="latest-additions">
        <h2>Latest Additions</h2>
        <div class="wa-grid wa-gap-2" style="--min-column-size: 200px;">
          {% for product in promoted_products %}
          <div>
            <wa-card class="card-overview">
              {% if product.images.first %}
              <img slot="media" src="{{ product.images.first.image.url }}" alt="{{ product.name }}" />
              {% else %}
              <img slot="media" src="https://via.placeholder.com/500x300?text=No+Image" alt="{{ product.name }}" />
              {% endif %}
              <h3>{{ product.name }}</h3>
              <p>£{{ product.price }}</p>
              <wa-button size='small' class='footer-btn' variant="brand" pill href="{% url 'store:product_detail' product.pk %}"><i class="fa-solid fa-bag-shopping"></i> Shop</wa-button>
            </wa-card>
          </div>
          {% empty %}
          <p>No promoted products to display.</p>
          {% endfor %}
          <wa-button size="large" class="latest-section-btn wa-span-grid" variant="brand" pill href="{% url 'store:store' %}">Shop All</wa-button>
        </div>
      </section>
      {% endblock latestAdditions %}
      {% block blogAndEvents %}
      {% comment %} blog and event section here {% endcomment %}
      {% endblock blogAndEvents %}
      {% block content %}
      {% comment %} content goes here {% endcomment %}
      {% endblock content %}
      {% block testimonials %}
      {% comment %} testimonials cards go here {% endcomment %}
      {% endblock testimonials %}
    </main>
<footer>
  <div class="navbar footer-container">
    <div class="footer-brand-section">
      <wa-button appearance='plain' size='large'>LittleGemFelts</wa-button>
      <div class="footer-social">
        <wa-button appearance='plain' size='small'>
          <i class="fa-brands fa-instagram"></i>
        </wa-button>
        <wa-button appearance='plain' size='small'>
          <i class="fa-brands fa-facebook"></i>
        </wa-button>
        
      </div>
    </div>
    <div class=" footer-link-section">
    <div class="footer-links">
      <ul class='menu'>
        <li><wa-button class='nav-btn'>One</wa-button></li>
        <li><wa-button class='nav-btn'>Two</wa-button></li>
        <li><wa-button class='nav-btn'>Three</wa-button></li>
      </ul>
    </div>
    <div class="footer-links">
      <ul class='menu'>
        <li><wa-button class='nav-btn'>1</wa-button></li>
        <li><wa-button class='nav-btn'>2</wa-button></li>
        <li><wa-button class='nav-btn'>3</wa-button></li>
      </ul>
    </div>
    <div class="footer-links">
      <ul class='menu'>
        <li><wa-button class='nav-btn'>4</wa-button></li>
        <li><wa-button class='nav-btn'>5</wa-button></li>
        <li><wa-button class='nav-btn'>6</wa-button></li>
      </ul>
    </div>
      </div>
  </div>
</footer>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'js/toasts.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script type =text/javascript>
      {% for message in messages %}
     Toastify({
        text: "{{message|escapejs}}",
        duration: 3000,
        destination: "https://github.com/apvarun/toastify-js",
        newWindow: true,
        close: true,
        gravity: "top", // `top` or `bottom`
        position: "left", // `left`, `center` or `right`
        stopOnFocus: true, // Prevents dismissing of toast on hover
        style: {
            background: "linear-gradient(to right, #00b09b, #96c93d)",//put custom colors here
        },
        onClick: function(){} // Callback after click
    }).showToast();
    {% endfor %}
    </script>
    {% block extra_js %}
    {% comment %} extra page JS loaded here {% endcomment %}
    {% endblock extra_js %}
      
</body>
</html>